# Generated by Django 4.2.6 on 2023-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=80)),
                ('Lastname', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=80)),
                ('Address2', models.CharField(blank=True, max_length=80, null=True)),
                ('Zip_code', models.IntegerField()),
                ('State', models.CharField(max_length=80)),
                ('Image', models.FileField(upload_to='')),
                ('Date_checkIn', models.DateField()),
                ('Time_checkIn', models.TimeField()),
                ('Date_checkOut', models.DateField()),
                ('Time_checkOut', models.TimeField()),
            ],
        ),
    ]
