# Generated by Django 4.2.6 on 2023-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_alter_reservation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
